=== Valentine14th/rbtlog/schemas/log.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/obfusk/rbtlog/log/schemas/log.json",
  "title": "rbtlog app rebuild log",
  "description": "rbtlog JSON app rebuild log (logs/*.json)",
  "type": "object",
  "properties": {
    "appid": {
      "description": "APK appid",
      "type": "string"
    },
    "notes": {
      "description": "notes (not required)",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "appid": {
              "description": "APK appid",
              "type": "string"
            },
            "notes": {
              "description": "notes (not required)",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "version_code": {
              "description": "APK version code",
              "type": [
                "integer",
                "null"
              ]
            },
            "version_name": {
              "description": "APK version name",
              "type": [
                "string",
                "null"
              ]
            },
            "tag": {
              "description": "git tag",
              "type": "string"
            },
            "commit": {
              "description": "hash of the commit the tag points to",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{40}$"
            },
            "recipe": {
              "type": "object",
              "properties": {
                "repository": {
                  "description": "git repository URL",
                  "type": "string",
                  "pattern": "^https://.*\\.git$"
                },
                "tag": {
                  "description": "git tag",
                  "type": "string"
                },
                "apk_pattern": {
                  "description": "regex to match against the release assets APK file names",
                  "type": "string"
                },
                "apk_url": {
                  "description": "APK download URL",
                  "type": "string",
                  "pattern": "^https://.*\\.(apk|zip)$"
                },
                "build": {
                  "description": "build recipe (lines of a bash script)",
                  "type": "string"
                },
                "build_cpus": {
                  "description": "number of CPUs to use for build (not required, default: null, older logs don't have this)",
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "build_home_dir": {
                  "description": "home directory for the build user",
                  "type": "string"
                },
                "build_repo_dir": {
                  "description": "directory the repo is cloned to and the build is run in",
                  "type": "string"
                },
                "build_timeout": {
                  "description": "build timeout in minutes (not required, default: null, older logs don't have this)",
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "build_user": {
                  "description": "build user name",
                  "type": "string"
                },
                "provisioning": {
                  "type": "object",
                  "properties": {
                    "android_home": {
                      "description": "android SDK directory",
                      "type": "string"
                    },
                    "build_tools": {
                      "description": "optional Android SDK build-tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "cmake": {
                      "description": "optional Android SDK cmake version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "cmdline_tools": {
                      "description": "Android SDK cmdline-tools specification",
                      "type": "object",
                      "properties": {
                        "version": {
                          "description": "Android cmdline-tools version",
                          "type": "string"
                        },
                        "url": {
                          "description": "download URL",
                          "type": "string",
                          "pattern": "^https://.*$"
                        },
                        "sha256": {
                          "description": "SHA-256 checksum (hex)",
                          "type": "string",
                          "pattern": "^[0-9a-f]{64}$"
                        }
                      },
                      "required": [
                        "version",
                        "url",
                        "sha256"
                      ],
                      "additionalProperties": false
                    },
                    "extra_packages": {
                      "description": "extra packages to install",
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "image": {
                      "description": "docker/podman image",
                      "type": "string"
                    },
                    "jdk": {
                      "description": "jdk package",
                      "type": "string"
                    },
                    "ndk": {
                      "description": "optional Android NDK version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "platform": {
                      "description": "optional Android SDK version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "platform_tools": {
                      "description": "optional Android SDK platform-tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "tools": {
                      "description": "optional Android SDK tools version",
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "verify_git": {
                      "description": "whether to verify git objects (not required, older logs don't have this)",
                      "type": "boolean"
                    },
                    "verify_gradle_wrapper": {
                      "description": "whether to verify the gradle-wrapper.jar checksum (not required, older logs don't have this)",
                      "type": "boolean"
                    },
                    "windows_like": {
                      "description": "whether to disable symlinks for git (not required, default: false, older logs don't have this)",
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "android_home",
                    "build_tools",
                    "cmake",
                    "cmdline_tools",
                    "extra_packages",
                    "image",
                    "jdk",
                    "ndk",
                    "platform",
                    "platform_tools",
                    "tools"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "repository",
                "tag",
                "apk_pattern",
                "apk_url",
                "build",
                "build_home_dir",
                "build_repo_dir",
                "build_user",
                "provisioning"
              ],
              "additionalProperties": false
            },
            "timestamp": {
              "description": "build timestamp",
              "type": "integer"
            },
            "cpu_count": {
              "description": "build host CPU count (not required, older logs don't have this)",
              "type": [
                "integer",
                "null"
              ]
            },
            "reproducible": {
              "description": "reproducibility test result",
              "type": [
                "boolean",
                "null"
              ]
            },
            "error": {
              "description": "error message",
              "type": [
                "string",
                "null"
              ]
            },
            "build_log": {
              "description": "build log",
              "type": "string"
            },
            "upstream_signed_apk_sha256": {
              "description": "SHA-256 checksum (hex) of upsteam APK",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            },
            "built_unsigned_apk_sha256": {
              "description": "SHA-256 checksum (hex) of built unsigned APK",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            },
            "signature_copied_apk_sha256": {
              "description": "SHA-256 checksum (hex) of APK with signature copied",
              "type": [
                "string",
                "null"
              ],
              "pattern": "^[0-9a-f]{64}$"
            }
          },
          "required": [
            "appid",
            "version_code",
            "version_name",
            "tag",
            "commit",
            "recipe",
            "timestamp",
            "reproducible",
            "error",
            "build_log",
            "upstream_signed_apk_sha256",
            "built_unsigned_apk_sha256",
            "signature_copied_apk_sha256"
          ],
          "additionalProperties": false
        }
      }
    },
    "version_codes": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "sha256": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[0-9a-f]{64}$"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "appid",
    "tags",
    "version_codes",
    "sha256"
  ],
  "additionalProperties": false
}

=== Valentine14th/rbtlog/logs/org.fossify.calculator.json
{
  "appid": "org.fossify.calculator",
  "tags": {
    "1.0.1": [
      {
        "appid": "org.fossify.calculator",
        "version_code": 2,
        "version_name": "1.0.1",
        "tag": "1.0.1",
        "commit": "c2a9092cc2f4a284022b44b53a29846a77a30f9b",
        "recipe": {
          "repository": "https://github.com/FossifyOrg/Calculator.git",
          "tag": "1.0.1",
          "apk_pattern": "calculator-\\d+-foss-release\\.apk",
          "apk_url": "https://github.com/FossifyOrg/Calculator/releases/download/1.0.1/calculator-2-foss-release.apk",
          "build": "DEX_FILE=app/build/intermediates/dex/fossRelease/minifyFossReleaseWithR8/classes.dex\nDEX_SHA1=5e26a6cf4b5f0f0fb139333b7d34b0a10a939331\nfor _ in {1..10}; do\n./gradlew clean assembleFossRelease --no-build-cache --no-configuration-cache --no-daemon\nif [ \"$( sha1sum \"$DEX_FILE\" | cut -d' ' -f1 )\" = \"$DEX_SHA1\" ]; then\nbreak\nfi\ndone\nmv app/build/outputs/apk/foss/release/calculator-*-foss-release-unsigned.apk /outputs/unsigned.apk\n",
          "build_home_dir": "/build",
          "build_repo_dir": "/build/repo",
          "build_user": "build",
          "provisioning": {
            "android_home": "/opt/sdk",
            "build_tools": null,
            "cmake": null,
            "cmdline_tools": {
              "version": "12.0",
              "url": "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip",
              "sha256": "2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258"
            },
            "extra_packages": [],
            "image": "debian:bookworm-slim",
            "jdk": "openjdk-17-jdk-headless",
            "ndk": null,
            "platform": null,
            "platform_tools": null,
            "tools": null,
            "verify_gradle_wrapper": true,
            "windows_like": false
          }
        },
        "timestamp": 1722209831,
        "reproducible": true,
        "error": null,
        "build_log": "RUN COMMAND podman pull -- debian:bookworm-slim\nResolved \"debian\" as an alias (/etc/containers/registries.conf.d/shortnames.conf)\nTrying to pull docker.io/library/debian:bookworm-slim...\nGetting image source signatures\nCopying blob sha256:efc2b5ad9eec05befa54239d53feeae3569ccbef689aa5e5dbfc25da6c4df559\nCopying blob sha256:efc2b5ad9eec05befa54239d53feeae3569ccbef689aa5e5dbfc25da6c4df559\nCopying config sha256:765d2dd7df99cbc197e164edc14c583969ef47f32819eb8bafa9bc8aadd2dbe7\nWriting manifest to image destination\nStoring signatures\n765d2dd7df99cbc197e164edc14c583969ef47f32819eb8bafa9bc8aadd2dbe7\nRUN COMMAND podman run --rm --volume /tmp/tmplq7v0ob2/outputs:/outputs --volume /tmp/tmplq7v0ob2/scripts:/scripts:ro --env ANDROID_HOME=/opt/sdk --env APP_REPOSITORY=https://github.com/FossifyOrg/Calculator.git --env APP_TAG=1.0.1 --env APP_COMMIT=c2a9092cc2f4a284022b44b53a29846a77a30f9b --env BUILD_USER=build --env BUILD_HOME_DIR=/build --env BUILD_REPO_DIR=/build/repo --env PROVISIONING_BUILD_TOOLS= --env PROVISIONING_CMAKE= --env PROVISIONING_CMDLINE_TOOLS_VERSION=12.0 --env PROVISIONING_CMDLINE_TOOLS_URL=https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip --env PROVISIONING_CMDLINE_TOOLS_SHA256=2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258 --env PROVISIONING_EXTRA_PACKAGES= --env PROVISIONING_JDK=openjdk-17-jdk-headless --env PROVISIONING_NDK= --env PROVISIONING_PLATFORM= --env PROVISIONING_PLATFORM_TOOLS= --env PROVISIONING_TOOLS= --env VERIFY_GRADLE_WRAPPER=yes --env WINDOWS_LIKE=no -- debian:bookworm-slim bash -c timeout 10m /scripts/provision-root.sh && cd /build && timeout 10m su build /scripts/provision.sh && cd /build/repo && timeout 20m su build /scripts/build.sh\n+ export DEBIAN_FRONTEND=noninteractive\n+ DEBIAN_FRONTEND=noninteractive\n+ apt-get update\nGet:1 http://deb.debian.org/debian bookworm InRelease [151 kB]\nGet:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]\nGet:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]\nGet:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8788 kB]\nGet:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]\nGet:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [169 kB]\nFetched 9225 kB in 1s (10.0 MB/s)\nReading package lists...\n+ apt-get upgrade -y\nReading package lists...\nBuilding dependency tree...\nReading state information...\nCalculating upgrade...\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n+ readarray -d , -t extra_packages\n++ printf %s ''\n+ apt-get install --no-install-recommends -y git wget unzip openjdk-17-jdk-headless\nReading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  ca-certificates ca-certificates-java fontconfig-config fonts-dejavu-core\n  git-man java-common libasound2 libasound2-data libavahi-client3\n  libavahi-common-data libavahi-common3 libbrotli1 libcups2 libcurl3-gnutls\n  libdbus-1-3 liberror-perl libexpat1 libfontconfig1 libfreetype6\n  libgdbm-compat4 libgdbm6 libglib2.0-0 libgraphite2-3 libgssapi-krb5-2\n  libharfbuzz0b libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3\n  libkrb5support0 liblcms2-2 libldap-2.5-0 libnghttp2-14 libnspr4 libnss3\n  libpcsclite1 libperl5.36 libpng16-16 libpsl5 librtmp1 libsasl2-2\n  libsasl2-modules-db libsqlite3-0 libssh2-1 libssl3 openjdk-17-jre-headless\n  openssl perl perl-modules-5.36\nSuggested packages:\n  gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-email git-gui\n  gitk gitweb git-cvs git-mediawiki git-svn default-jre libasound2-plugins\n  alsa-utils cups-common gdbm-l10n low-memory-monitor krb5-doc krb5-user\n  liblcms2-utils pcscd sensible-utils openjdk-17-demo openjdk-17-source\n  libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho\n  fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic perl-doc\n  libterm-readline-gnu-perl | libterm-readline-perl-perl make\n  libtap-harness-archive-perl zip\nRecommended packages:\n  patch less ssh-client alsa-ucm-conf alsa-topology-conf dbus libglib2.0-data\n  shared-mime-info xdg-user-dirs krb5-locales libldap-common publicsuffix\n  libsasl2-modules netbase\nThe following NEW packages will be installed:\n  ca-certificates ca-certificates-java fontconfig-config fonts-dejavu-core git\n  git-man java-common libasound2 libasound2-data libavahi-client3\n  libavahi-common-data libavahi-common3 libbrotli1 libcups2 libcurl3-gnutls\n  libdbus-1-3 liberror-perl libexpat1 libfontconfig1 libfreetype6\n  libgdbm-compat4 libgdbm6 libglib2.0-0 libgraphite2-3 libgssapi-krb5-2\n  libharfbuzz0b libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3\n  libkrb5support0 liblcms2-2 libldap-2.5-0 libnghttp2-14 libnspr4 libnss3\n  libpcsclite1 libperl5.36 libpng16-16 libpsl5 librtmp1 libsasl2-2\n  libsasl2-modules-db libsqlite3-0 libssh2-1 libssl3 openjdk-17-jdk-headless\n  openjdk-17-jre-headless openssl perl perl-modules-5.36 unzip wget\n0 upgraded, 53 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 148 MB of archives.\nAfter this operation, 410 MB of additional disk space will be used.\nGet:1 http://deb.debian.org/debian bookworm/main amd64 perl-modules-5.36 all 5.36.0-7+deb12u1 [2815 kB]\nGet:2 http://deb.debian.org/debian bookworm/main amd64 libgdbm6 amd64 1.23-3 [72.2 kB]\nGet:3 http://deb.debian.org/debian bookworm/main amd64 libgdbm-compat4 amd64 1.23-3 [48.2 kB]\nGet:4 http://deb.debian.org/debian bookworm/main amd64 libperl5.36 amd64 5.36.0-7+deb12u1 [4218 kB]\nGet:5 http://deb.debian.org/debian bookworm/main amd64 perl amd64 5.36.0-7+deb12u1 [239 kB]\nGet:6 http://deb.debian.org/debian bookworm/main amd64 libssl3 amd64 3.0.13-1~deb12u1 [2022 kB]\nGet:7 http://deb.debian.org/debian bookworm/main amd64 openssl amd64 3.0.13-1~deb12u1 [1418 kB]\nGet:8 http://deb.debian.org/debian bookworm/main amd64 ca-certificates all 20230311 [153 kB]\nGet:9 http://deb.debian.org/debian bookworm/main amd64 libpsl5 amd64 0.21.2-1 [58.7 kB]\nGet:10 http://deb.debian.org/debian bookworm/main amd64 wget amd64 1.21.3-1+b2 [984 kB]\nGet:11 http://deb.debian.org/debian bookworm/main amd64 ca-certificates-java all 20230710~deb12u1 [11.9 kB]\nGet:12 http://deb.debian.org/debian bookworm/main amd64 fonts-dejavu-core all 2.37-6 [1068 kB]\nGet:13 http://deb.debian.org/debian bookworm/main amd64 fontconfig-config amd64 2.14.1-4 [315 kB]\nGet:14 http://deb.debian.org/debian bookworm/main amd64 libbrotli1 amd64 1.0.9-2+b6 [275 kB]\nGet:15 http://deb.debian.org/debian-security bookworm-security/main amd64 libkrb5support0 amd64 1.20.1-2+deb12u2 [32.6 kB]\nGet:16 http://deb.debian.org/debian-security bookworm-security/main amd64 libk5crypto3 amd64 1.20.1-2+deb12u2 [78.7 kB]\nGet:17 http://deb.debian.org/debian bookworm/main amd64 libkeyutils1 amd64 1.6.3-2 [8808 B]\nGet:18 http://deb.debian.org/debian-security bookworm-security/main amd64 libkrb5-3 amd64 1.20.1-2+deb12u2 [332 kB]\nGet:19 http://deb.debian.org/debian-security bookworm-security/main amd64 libgssapi-krb5-2 amd64 1.20.1-2+deb12u2 [135 kB]\nGet:20 http://deb.debian.org/debian bookworm/main amd64 libsasl2-modules-db amd64 2.1.28+dfsg-10 [20.3 kB]\nGet:21 http://deb.debian.org/debian bookworm/main amd64 libsasl2-2 amd64 2.1.28+dfsg-10 [59.7 kB]\nGet:22 http://deb.debian.org/debian bookworm/main amd64 libldap-2.5-0 amd64 2.5.13+dfsg-5 [183 kB]\nGet:23 http://deb.debian.org/debian bookworm/main amd64 libnghttp2-14 amd64 1.52.0-1+deb12u1 [72.4 kB]\nGet:24 http://deb.debian.org/debian bookworm/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-2+b2 [60.8 kB]\nGet:25 http://deb.debian.org/debian bookworm/main amd64 libssh2-1 amd64 1.10.0-3+b1 [179 kB]\nGet:26 http://deb.debian.org/debian bookworm/main amd64 libcurl3-gnutls amd64 7.88.1-10+deb12u6 [385 kB]\nGet:27 http://deb.debian.org/debian bookworm/main amd64 libexpat1 amd64 2.5.0-1 [99.3 kB]\nGet:28 http://deb.debian
